### ISSUE TITLE
Publish Maven site to GitHub Pages

### ISSUE THREAD

**Issue by smola** [Stratio/scala-cross-build-maven-plugin#14]
See https://github.github.com/maven-plugins/site-plugin/

**Comment by witokondoria** [comment]
Implemented at continuous delivery pipeline. need to include scm tag (so it doesnt inherit from stratio-parent):

<scm>
        <url>https://github.com/Stratio/</url>
        <connection>scm:git:git@github.com:Stratio/scala-cross-build-maven-plugin.git</connection>
        <developerConnection>scm:git:git@github.com:Stratio/scala-cross-build-maven-plugin.git
        </developerConnection>
        <tag>HEAD</tag>
    </scm>  

Published to s3

**Comment by witokondoria** [comment]
http://stratiodocs.s3-website-us-east-1.amazonaws.com/crossbuilds-maven-plugin/0.2.0-SNAPSHOT/
